### ISSUE TITLE
Add generated date/time stamp to visible footer?

### ISSUE THREAD

**Issue by seancorfield** [clojuredocs/guides#157]
It would be nice to know when the web site was last generated from source, so that visitors could get a sense of how up-to-date it is compared to what's on Github.

I don't know if the generation process could automatically generate a date/time stamp into the page layout footer?

**Comment by seancorfield** [comment]
Any more thoughts on this?

**Comment by michaelklishin** [comment]
This [seems easy enough](https://stackoverflow.com/questions/36758072/how-to-insert-the-last-updated-time-stamp-in-jekyll-page-at-build-time) with a tiny Jekyll plugin.

**Comment by seancorfield** [comment]
OK, if I get a chance this weekend, I'll try that out. It's been a while since I tried to build clojure-doc locally (I seem to recall getting into a mess with my two octopress sites, last time I tried to get clojure-doc building... I hate Ruby for that sort of mess!).
