### ISSUE TITLE
Some clarity into Layout of Functions pseudocode example

### ISSUE THREAD

**Issue by duhovny** [clojuredocs/guides#175]
It says that:

> Clojure doesn't like [writing functions in a top-down fashion] because it wants to have at least heard about a function before you write a call to it.

However, the following example starts with:

```
(do-it)
```

without using:

```
(declare do-it)
```

earlier.

I might be wrong (of course! I'm just getting started), but shouldn't the example declare do-it before calling it, for clarity?

Thanks a lot for your work!

**Comment by seancorfield** [comment]
This seems to have been fixed at some point: http://clojure-doc.org/articles/tutorials/introduction.html#layout-of-functions -- the first example is clearly labeled as "BROKEN" and the second example shows `(declare do-it)` to fix the problem. Closing.
