### ISSUE TITLE
add "see also" links to lang/glossary pointing to other cds docs

### ISSUE THREAD

**Issue by uvtc** [clojuredocs/guides#20]
The glossary could use additional "see also" links pointing to other cds docs which cover the term in question (though perhaps some of those other cds docs (or sections thereof) may not've been written yet).

Links in a given definition could point to either another term section heading in the glossary, or else to the relevant section of another doc. For simplicity and consistency, it might be best to follow the convention of only linking to other cds docs' relevant sections from the particular term in question: For example: in the definition of "lazy", link to glossary/#persistence, and from glossary/#persistence link to tut/intro/#persistence section (rather than directly from the definition section of "lazy").

**Comment by seancorfield** [comment]
It looks like the Glossary cross-links terms fairly comprehensively now, and I see several links to other parts of CDS and to other external material.

I think this issue can be closed now.

If you have _specific_ changes you'd like to see, you can open new issues with more detail or, preferably, send PRs that would add more links.
