### ISSUE TITLE
add definitions to glossary for items containing only "todo"

### ISSUE THREAD

**Issue by uvtc** [clojuredocs/guides#21]
For a handful of terms I didn't know a good definition. Add definitions for these.

**Comment by seancorfield** [comment]
I'm am resurrecting this site at https://clojure-doc.github.io so feel free to create new issues at https://github.com/clojure-doc/clojure-doc.github.io/issues or submit a PR https://github.com/clojure-doc/clojure-doc.github.io/pulls
