### ISSUE TITLE
jdbc/query! doesn't exist

### ISSUE THREAD

**Issue by germanoid** [clojuredocs/guides#212]
https://github.com/clojuredocs/guides/blob/master/articles/ecosystem/java_jdbc/home.md
has a typo in

    (jdbc/query!  db-spec ["SELECT * FROM table WHERE id = ?" 13]) ;; Read

It should be

    (jdbc/query  db-spec ["SELECT * FROM table WHERE id = ?" 13]) ;; Read

**Comment by seancorfield** [comment]
Could we get a new version of the site published? Someone else just reported this typo to me and I realized it had been fixed a while back but the site hadn't been updated. Thanks!

**Comment by michaelklishin** [comment]
@seancorfield done.

**Comment by seancorfield** [comment]
:+1:
