### ISSUE TITLE
MELPA code in Emacs tutorial returns error

### ISSUE THREAD

**Issue by plt6356** [clojuredocs/guides#213]
Hello. When I insert this code for installing MELPA packages from the Emacs tutorial (http://clojure-doc.org/articles/tutorials/emacs.html) into ~/.emacs.d/init.el:

cl (require 'package) (add-to-list 'package-archives '("melpa-stable" . "http://stable.melpa.org/packages/") t) (package-initialize)

I get the following error message on Emacs startup:

Warning (initialization): An error occurred while loading `/home/alyssavance/.emacs.d/init.el':

Symbol's value as variable is void: cl

This is using Emacs 24.4.1 on Ubuntu 15.04 (Vivid). This alternative code from MELPA's Github page (https://github.com/milkypostman/melpa) works fine:

(require 'package)
(add-to-list 'package-archives
             '("melpa" . "http://melpa.org/packages/") t)
(when (< emacs-major-version 24)
  ;; For important compatibility libraries like cl-lib
  (add-to-list 'package-archives '("gnu" . "http://elpa.gnu.org/packages/")))
(package-initialize)

**Comment by michaelklishin** [comment]
``` emacs
(require 'cl)
```

is missing somewhere. I'm not sure where but using stable melpa package sounds like a sensible recommendation in general.
