### ISSUE TITLE
Catch exceptions thrown by postgresql

### ISSUE THREAD

**Issue by ProbonoBonobo** [clojuredocs/guides#221]
I'm trying to get acquainted with Clojure syntax for basic CRUD operations is all. Unfortunately I'm hitting an impasse with errors like these:
```
shouter.models.migration=> (sql/db-do-commands "postgresql://localhost:5432/sandbox"
                      #_=>                            (sql/create-table-ddl :testing [:data :text]))

BatchUpdateException Batch entry 0 CREATE TABLE testing (data text) was aborted.  Call getNextException to see the cause.  org.postgresql.jdbc2.AbstractJdbc2Statement$BatchResultHandler.handleError (AbstractJdbc2Statement.java:2762)
```

How do I call "getNextException" from the Clojure environment? Whose method is it? I found lots of people asking about this (several were jbdc users), but the solutions I found required wrapping the transaction in a clojure.java.jdbc/with-connection method. That method is since deprecated.

I'd encourage you to put the answer prominently in the docs. For instance [this page](http://clojure-doc.org/articles/ecosystem/java_jdbc/using_ddl.html) is suitable as an introduction to Clojure DDL syntax, except it doesn't mention postgresql throws errors in the underlying Java, or tell you how to read those errors. I wouldn't assume all of your readers have the requisite Java proficiency to read them on our own. Many of us chose Clojure precisely to avoid Java :-).

**Comment by michaelklishin** [comment]
We won't be able to cover every potential issue. While we are at it, if you use Clojure to avoid Java, you'd be disillusioned fairly quickly: Clojure doesn't try to hide Java and the whole idea is not very wise.
