### ISSUE TITLE
Update java.jdbc documentation to match 0.7.0

### ISSUE THREAD

**Issue by seancorfield** [clojuredocs/guides#229]
See http://dev.clojure.org/jira/browse/JDBC-139 and earlier changes.

This is a placeholder / reminder for myself to make the necessary changes.

**Comment by ehashman** [comment]
I'd be happy to work on this sometime.

**Comment by michaelklishin** [comment]
@ehashman that would be really appreciated :)

**Comment by seancorfield** [comment]
@ehashman I just updated Using DDL and Using SQL a little -- just to match the 0.7.0 API (`insert-multi!`, options in hash maps, etc). The whole processing lazy result set/rows section ought to be replaced by `reducible-query` at this point I think.

**Comment by seancorfield** [comment]
This work is now complete -- I think everything changed between 0.6.x and 0.7.x is documented now, including several examples of `reducible-query`.

@michaelklishin Not sure often you deploy/rebuild the site, but it would be nice to get these changes live soon -- thank you!
