### ISSUE TITLE
Outdated info in Emacs section

### ISSUE THREAD

**Issue by Compro-Prasad** [clojuredocs/guides#237]
`C-c ,` doesn't seem to be supported in *CIDER* for running tests. Instead I am using `C-c C-t t` to run tests which I didn't configure myself at all.

And I am not using `better-defaults`. Is that a problem.

`C-c '` too was not working. Maybe I can't reproduce the situation.

`Leiningen 2.7.1 on Java 1.7.0_131 OpenJDK 64-Bit Server VM`
`GNU Emacs 25.1.1`
`Clojure 1.8.0`
articles/tutorials/emacs.md

**Comment by michaelklishin** [comment]
@Compro-Prasad please make sure that you are running the most recent version of the Clojure modes and if that's the case feel free to submit a pull request.

**Comment by Compro-Prasad** [comment]
Would be better if its confirmed that `C-c C-t t` is the default key binding or it would be useless.

**Comment by michaelklishin** [comment]
I'm not sure what you mean by "confirmed." Key bindings change between releases of Emacs packages. Feel free to verify that what you use is the default in the most recent release available and then submit a pull request.
