### ISSUE TITLE
Integration with Klipse

### ISSUE THREAD

**Issue by viebel** [clojuredocs/guides#264]
I’d like to discuss with you guys about the idea of integrating Klipse in order to feature interactive code snippets in clojure-doc.org

**Comment by seancorfield** [comment]
I'm am resurrecting this site at https://clojure-doc.github.io so feel free to recreate this issue at https://github.com/clojure-doc/clojure-doc.github.io/issues or submit a PR https://github.com/clojure-doc/clojure-doc.github.io/pulls -- I notice that Cryogen has a configuration for Klipse but I've never tried it so feel free to help guide me over at the new site.

**Comment by viebel** [comment]
Opened a new issue https://github.com/clojure-doc/clojure-doc.github.io/issues/12
