### ISSUE TITLE
Outdated macOS Emacs instructions

### ISSUE THREAD

**Issue by michaelteter** [clojuredocs/guides#265]
The instructions say `brew install --with-cocoa`, but _--with-cocoa_ is rejected by brew.

Then it says `brew linkapps Emacs`, but brew says _linkapps_ is an unknown command.

There are quite a few different opinions on how to install it, but one that currently works and provides a GUI is `brew cask install emacs`.  It also sets up the links so Spotlight can find and launch Emacs.

**Comment by michaelklishin** [comment]
Please submit a PR. Installing via a cask sounds good to me.

**Comment by michaelteter** [comment]
Done.  This is the first time I've done this, so pardon me if I did the Git process strangely.

**Comment by seancorfield** [comment]
Fixed by #266 awaiting build of the website.
