### ISSUE TITLE
Point clojure-doc.org at new GitHub pages domain?

### ISSUE THREAD

**Issue by seancorfield** [clojuredocs/guides#278]
@michaelklishin I don't know if you still have access to the domain configuration for clojure-doc.org but if you do, would you consider pointing it at the new GH version?

```
clojure-doc.github.io.	3600	IN	A	185.199.111.153
clojure-doc.github.io.	3600	IN	A	185.199.109.153
clojure-doc.github.io.	3600	IN	A	185.199.110.153
clojure-doc.github.io.	3600	IN	A	185.199.108.153
```

**Comment by seancorfield** [comment]
@michaelklishin ?

**Comment by michaelklishin** [comment]
Done.

**Comment by seancorfield** [comment]
Much appreciated! I am enabling that domain on the GH pages site. As soon as the SSL certificate has propagated, I will switch it to SSL only.

**Comment by seancorfield** [comment]
@michaelklishin There appears to be a problem with the DNS changes -- GitHub Pages is failing to create the TLS certificate. This community post covers some of the issues -- could you take a look? https://github.community/t/certificate-request-error-is-persistent-tls-certificate-cant-be-provisioned/11008/15

**Comment by seancorfield** [comment]
As an example, here's how I have corfield.org set up to point to GitHub Pages: https://www.dropbox.com/s/ucmwyf4cdz42lv3/Screen%20Shot%202022-02-16%20at%209.43.11%20PM.png?dl=0

and I also have: 

```
CNAME | www | corfield.org.
```

So perhaps that's the missing piece for your setup?

**Comment by seancorfield** [comment]
This all appears to be working now. Thank you.
